### ISSUE TITLE
Exercise week 1

### ISSUE THREAD

**Issue by s-a-m-u** [sta426hs2017/material#15]
Dear @markrobinsonuzh,

Please find the repository with the homework for week one here: https://github.com/s-a-m-u/sta426_Exercise_1

Kind regards,

Samuel

**Comment by markrobinsonuzh** [comment]
Great.  Please also submit the Rmd file, not just the HTML.

**Comment by s-a-m-u** [comment]
Thanks, I've updated the repository with the rmd file.
