### ISSUE TITLE
HW2 & HW1-part 2

### ISSUE THREAD

**Issue by orangelc1221** [sta426hs2017/material#21]
HW1 part 2: https://github.com/orangelc1221/sta46/tree/master/hw1
HW2: https://github.com/orangelc1221/sta46/tree/master/hw2 
Thanks!

Cheng Li

**Comment by markrobinsonuzh** [comment]
As discussed in class, Exercise 2 is to be submitted via the github classroom, not in your own personal github repo.

Homework 1 looks nice.
